/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmicalculator;

/**
 *
 * @author Admin
 */
public class Menaikan extends javax.swing.JFrame {

    /**
     * Creates new form Menaikan
     */
    public Menaikan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tinggi = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Tinggi1 = new javax.swing.JLabel();
        Tinggi2 = new javax.swing.JLabel();
        Tinggi3 = new javax.swing.JLabel();
        Tinggi4 = new javax.swing.JLabel();
        Tinggi5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tinggi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi.setText("Tips Menaikan Berat Badan");
        getContentPane().add(Tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 412, 133, -1));

        Tinggi1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi1.setText("1. Perbanyak minum air putih");
        getContentPane().add(Tinggi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 142, -1, -1));

        Tinggi2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi2.setText("2. Berhenti Merokok ");
        getContentPane().add(Tinggi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 191, -1, -1));

        Tinggi3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi3.setText("3. Rutin berolahraga");
        getContentPane().add(Tinggi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 240, -1, -1));

        Tinggi4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi4.setText("5. Perbanyak memakan makanan bernutrisi");
        getContentPane().add(Tinggi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 331, -1, -1));

        Tinggi5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Tinggi5.setText("4. Rutin Meminum Susu");
        getContentPane().add(Tinggi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 282, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\gambar nya\\bckgrnd.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Utama utm=new Utama();
        utm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menaikan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tinggi;
    private javax.swing.JLabel Tinggi1;
    private javax.swing.JLabel Tinggi2;
    private javax.swing.JLabel Tinggi3;
    private javax.swing.JLabel Tinggi4;
    private javax.swing.JLabel Tinggi5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
